<Project Sdk="Microsoft.NET.Sdk">

  <ItemGroup>
    <ProjectReference Include="..\RemoteEternal.Core\RemoteEternal.Core.csproj" />
  </ItemGroup>

  <ItemGroup>
    <PackageReference Include="FFmpeg.AutoGen" Version="8.1.0" />
    <PackageReference Include="NAudio" Version="2.3.0" />
    <PackageReference Include="ScreenRecorderLib" Version="6.6.0" />
  </ItemGroup>

  <PropertyGroup>
    <OutputType>WinExe</OutputType>
    <TargetFramework>net8.0-windows</TargetFramework>
    <Nullable>enable</Nullable>
    <ImplicitUsings>enable</ImplicitUsings>
    <UseWPF>true</UseWPF>
    <AllowUnsafeBlocks>true</AllowUnsafeBlocks>
    <AssemblyName>RemoteEternal</AssemblyName>
    <RootNamespace>RemoteEternal.App</RootNamespace>
    <Platforms>x64</Platforms>
    <PlatformTarget>x64</PlatformTarget>
    <Platform Condition="'$(Platform)' == '' or '$(Platform)' == 'AnyCPU'">x64</Platform>
  </PropertyGroup>

  <ItemGroup Condition="Exists('..\..\libs\ffmpeg\bin')">
    <None Include="..\..\libs\ffmpeg\bin\*.dll" CopyToOutputDirectory="PreserveNewest" Link="ffmpeg\%(Filename)%(Extension)" />
  </ItemGroup>

</Project>
